# Generated by Django 2.2.5 on 2019-09-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medilov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='video title')),
                ('url', models.CharField(max_length=1000, unique=True, verbose_name='video url')),
                ('preview', models.CharField(max_length=1000, unique=True, verbose_name='img url')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='medilov.Gallery')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
    ]
