# Generated by Django 2.2.4 on 2019-08-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medilov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutunit',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='medilov.AboutUnit'),
        ),
    ]
